// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBotil-_BwhirfC5zdqHTQuLr9vbRo-U2E',
    appId: '1:226940671988:web:d8a465571c87ab76174ba1',
    messagingSenderId: '226940671988',
    projectId: 'fir-setup-454b8',
    authDomain: 'fir-setup-454b8.firebaseapp.com',
    storageBucket: 'fir-setup-454b8.appspot.com',
    measurementId: 'G-RSL1L5HW9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWl3j0ztwc_fQWmJEvAdTTIpkRvVnJ5_w',
    appId: '1:226940671988:android:284006b2215b245f174ba1',
    messagingSenderId: '226940671988',
    projectId: 'fir-setup-454b8',
    storageBucket: 'fir-setup-454b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALaTadMAVbdl5ThkDaz3elcoV4RHpu-gU',
    appId: '1:226940671988:ios:58d174b53f4e3326174ba1',
    messagingSenderId: '226940671988',
    projectId: 'fir-setup-454b8',
    storageBucket: 'fir-setup-454b8.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALaTadMAVbdl5ThkDaz3elcoV4RHpu-gU',
    appId: '1:226940671988:ios:58d174b53f4e3326174ba1',
    messagingSenderId: '226940671988',
    projectId: 'fir-setup-454b8',
    storageBucket: 'fir-setup-454b8.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBotil-_BwhirfC5zdqHTQuLr9vbRo-U2E',
    appId: '1:226940671988:web:9cd78f23af821d6e174ba1',
    messagingSenderId: '226940671988',
    projectId: 'fir-setup-454b8',
    authDomain: 'fir-setup-454b8.firebaseapp.com',
    storageBucket: 'fir-setup-454b8.appspot.com',
    measurementId: 'G-SDZQ1FGGM2',
  );
}
